### ISSUE TITLE
イベント機能の作成

### ISSUE THREAD

**Issue by mizukmb** [mizukmb/awesome_events#9]
- [x] event モデルのテストを書く
 - [x] name, place, start_time, end_time, content の記入は必須であること
 - [x] name は50文字以下であること
 - [x] place は100文字以下であること
 - [x] content は2000文字以下であること
 - [x] start_time は end_time よりも前の時間であること
- [x] event モデルを作成する
- [x] テストが通ることを確認する

**Comment by mizukmb** [comment]
```
Failures:

  1) Event#name 
     Failure/Error: it {should validate_presence_of(:name) }
     
     NoMethodError:
       undefined method `validate_presence_of' for #<RSpec::ExampleGroups::Event::Name:0x007f874b7bdd40>
     # ./spec/models/event_spec.rb:5:in `block (3 levels) in <top (required)>'

Finished in 0.00173 seconds (files took 6.06 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/event_spec.rb:5 # Event#name
```

は、 `spec/rails_helper.rb` に

```
RSpec.configure do |config|
 config.include(Shoulda::Matchers::ActiveModel, type: :model)
 config.include(Shoulda::Matchers::ActiveRecord, type: :model)
end
```

と記述すると解決する

**Comment by mizukmb** [comment]
`ensure_length_of` はv3.0.0より `validate_length_of` に rename されていた

http://stackoverflow.com/questions/33280731/shoulda-matchers-are-not-seen-by-rails-rspec
https://github.com/thoughtbot/shoulda-matchers/blob/55c8d09bf2af886540924efa83c3b518d926a770/NEWS.md

**Comment by a-know** [comment]
こういう、実際の作業（コードを伴う）をやりながら出てきたものは、
hanocha がやってるように、PR を作ってその中のコメントとして書いてくれたほうが
対応付けがわかりやすくていいかなー。

issue を使うと良さそうなのは、

* 作業に入る前にあらかじめ設計したり考えたりしたことを書く
* コードを伴わない作業をしながら、その作業メモとして利用する

とかっていったケースだろうか！

**Comment by mizukmb** [comment]
確かに issue に実装レベルの作業メモを書き残すのは違うように見えますね。
ありがとうございます！
